services:
  web:
    build:
      context: src/
      args:
        PIP_REQUIREMENTS: requirements_dev.txt
    ports:
      - "8098:8000"
    environment:
      UWSGI_STATIC_MAP: "/vertrouwelijke_data_proxy/static=/static"
      SECRET_KEY: insecure
      CORS_ALLOW_ALL_ORIGINS: "${CORS_ALLOW_ALL_ORIGINS:-true}"
      DJANGO_LOG_LEVEL: "${DJANGO_LOG_LEVEL:-INFO}"
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      OAUTH_JWKS_URL: "${OAUTH_JWKS_URL}"
      AZURE_STORAGE_CONTAINER_ENDPOINT: "${AZURE_STORAGE_CONTAINER_ENDPOINT}"
      DSO_API_BASE_URL: "${DSO_API_BASE_URL:-https://api.data.amsterdam.nl}"
      CLOUD_ENV: "${CLOUD_ENV:-local}"
      DJANGO_DEBUG: 1
    volumes:
      - ./src:/app
    command: uwsgi --py-auto-reload=1 --enable-threads --lazy-apps --buffer-size=65535
